//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uCommerceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVerified
    {
        public int Id { get; set; }
        public int AdminUserId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string IP { get; set; }
        public int ProductId { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
        public virtual Product Product { get; set; }
    }
}
